import type {
  AggregatedTokens,
  ComponentStyle,
  ElevationLevel,
} from "@/lib/extraction/types";

/**
 * Generates a DESIGN.md file from aggregated design tokens.
 * Follows the Google Stitch DESIGN.md format with extended sections
 * for Visual Theme, Component Stylings, Do's/Don'ts, and Agent Prompts.
 */
export function generateMarkdown(tokens: AggregatedTokens): string {
  const sections = [
    generateHeader(tokens),
    generateVisualTheme(tokens),
    generateColorPalette(tokens),
    generateTypography(tokens),
    generateComponentStylesSection(tokens),
    generateLayoutPrinciples(tokens),
    generateDepthAndElevation(tokens),
    generateDosAndDonts(tokens),
    generateResponsiveBehavior(tokens),
    generateAgentPromptGuide(tokens),
  ];

  return sections.join("\n\n");
}

// ── 0. Header ───────────────────────────────────────────────────────────────

function generateHeader(tokens: AggregatedTokens): string {
  const urlList = tokens.sourceUrls.map((u) => `- ${u}`).join("\n");
  const hostname = tokens.sourceUrls[0]
    ? new URL(tokens.sourceUrls[0]).hostname.replace("www.", "")
    : "Unknown";

  return `# Design System Extracted from ${hostname}

> **Auto-generated by Frontend DNA**
> Source${tokens.sourceUrls.length > 1 ? "s" : ""}:
${urlList}
>
> This file follows the DESIGN.md format. Drop it into your project root
> and any AI coding agent will understand how your UI should look.
> Generated: ${new Date().toISOString()}`;
}

// ── 1. Visual Theme & Atmosphere ────────────────────────────────────────────

function generateVisualTheme(tokens: AggregatedTokens): string {
  const { colors, typography, shadows, borders, spacing } = tokens;

  // Determine primary font
  const primaryFont = typography.fontFamilies[0]
    ? typography.fontFamilies[0].split(",")[0].trim().replace(/['"]/g, "")
    : "system font";

  // Determine dominant heading weight
  const headingEntries = typography.typeScale.filter((t) =>
    ["h1", "h2", "h3"].includes(t.element)
  );
  const dominantWeight = headingEntries[0]?.fontWeight || "400";

  // Determine primary brand color
  const primaryAccent =
    colors.palette.find((c) => c.usage === "accent") ||
    colors.palette.find((c) => c.usage === "text" && c.hex !== "#000000");
  const primaryBg = colors.backgrounds[0] || "#ffffff";

  // Determine if dark or light theme
  const isDark = isColorDark(primaryBg);

  // Analyze shadow complexity
  const shadowLayers = shadows.boxShadows.filter((s) => s.includes(",")).length;
  const hasSophisticatedShadows = shadowLayers > 0 || shadows.boxShadows.length > 3;

  // Border radius personality
  const radiiNums = borders.radii
    .map((r) => parseFloat(r))
    .filter((n) => !isNaN(n) && n > 0);
  const avgRadius = radiiNums.length
    ? radiiNums.reduce((a, b) => a + b, 0) / radiiNums.length
    : 0;
  const radiusPersonality =
    avgRadius > 16
      ? "generous, rounded"
      : avgRadius > 8
        ? "moderate, balanced"
        : avgRadius > 0
          ? "conservative, precise"
          : "sharp, geometric";

  // Spacing density
  const spacingDensity =
    spacing.scale.length > 10
      ? "dense, precision-oriented"
      : spacing.scale.length > 6
        ? "balanced"
        : "minimal, generous";

  let section = `## 1. Visual Theme & Atmosphere

The site presents a ${isDark ? "dark, immersive" : "clean, light"} interface built on a ${primaryBg} background`;

  if (primaryAccent) {
    section += ` with \`${primaryAccent.hex}\` as the primary accent color`;
  }

  section += `. The typography system is anchored by **${primaryFont}** at weight ${dominantWeight}`;

  if (parseInt(dominantWeight) <= 300) {
    section += ` — an unusually light weight that creates an elegant, confident presence without visual heaviness`;
  } else if (parseInt(dominantWeight) >= 700) {
    section += ` — bold and assertive, demanding attention`;
  }

  section += `.`;

  if (hasSophisticatedShadows) {
    section += ` The shadow system uses ${shadows.boxShadows.length > 1 ? "multi-layer" : "single-layer"} shadows that create atmospheric depth.`;
  }

  section += `

**Key Characteristics:**
- **Primary font:** \`${primaryFont}\` at weight ${dominantWeight}
- **Theme:** ${isDark ? "Dark" : "Light"} background (\`${primaryBg}\`)${primaryAccent ? `\n- **Accent color:** \`${primaryAccent.hex}\` — used for interactive and brand elements` : ""}
- **Border radius:** ${radiusPersonality} (avg ${avgRadius.toFixed(0)}px)
- **Spacing:** ${spacingDensity} scale: [${spacing.scale.join(", ")}]px
- **Shadow depth:** ${shadows.boxShadows.length} unique shadow${shadows.boxShadows.length !== 1 ? "s" : ""} extracted${hasSophisticatedShadows ? " (multi-layer)" : ""}
- **Typography scale:** ${typography.typeScale.length} distinct sizes from ${typography.typeScale[0]?.fontSize || "?"} down to ${typography.typeScale[typography.typeScale.length - 1]?.fontSize || "?"}`;

  if (typography.fontSources.length > 0) {
    section += `\n- **Font sources:** ${typography.fontSources.length > 0 ? "External fonts loaded" : "System fonts only"}`;
  }

  return section;
}

// ── 2. Color Palette & Roles ────────────────────────────────────────────────

function generateColorPalette(tokens: AggregatedTokens): string {
  const { colors } = tokens;

  let section = `## 2. Color Palette & Roles`;

  // Semantic groupings with role names
  const textColors = colors.palette.filter((c) => c.usage === "text").slice(0, 5);
  const bgColors = colors.palette.filter((c) => c.usage === "background").slice(0, 5);
  const borderColors = colors.palette.filter((c) => c.usage === "border").slice(0, 5);
  const accentColors = colors.palette.filter((c) => c.usage === "accent").slice(0, 3);

  if (textColors.length > 0) {
    section += `

### Text Colors
| Role | Hex | HSL | Frequency |
|------|-----|-----|-----------|
${textColors.map((c, i) => `| ${i === 0 ? "Primary heading" : i === 1 ? "Body text" : `Text ${i + 1}`} | \`${c.hex}\` | \`${c.hsl}\` | ${c.frequency}x |`).join("\n")}`;
  }

  if (bgColors.length > 0) {
    section += `

### Background Colors
| Role | Hex | HSL | Frequency |
|------|-----|-----|-----------|
${bgColors.map((c, i) => `| ${i === 0 ? "Primary surface" : i === 1 ? "Secondary surface" : `Surface ${i + 1}`} | \`${c.hex}\` | \`${c.hsl}\` | ${c.frequency}x |`).join("\n")}`;
  }

  if (accentColors.length > 0) {
    section += `

### Accent & Interactive
| Role | Hex | HSL | Frequency |
|------|-----|-----|-----------|
${accentColors.map((c, i) => `| ${i === 0 ? "Primary accent / CTA" : `Accent ${i + 1}`} | \`${c.hex}\` | \`${c.hsl}\` | ${c.frequency}x |`).join("\n")}`;
  }

  if (borderColors.length > 0) {
    section += `

### Border Colors
${borderColors.map((c) => `- \`${c.hex}\` (${c.frequency}x)`).join("\n")}`;
  }

  // CSS Variable Colors
  const varEntries = Object.entries(colors.cssVariableColors);
  if (varEntries.length > 0) {
    section += `

### CSS Custom Properties (Colors)
\`\`\`css
:root {
${varEntries.map(([k, v]) => `  ${k}: ${v};`).join("\n")}
}
\`\`\``;
  }

  // Conflicts
  if (tokens.conflicts.length > 0) {
    section += `

### Variable Conflicts (Multi-URL)
${tokens.conflicts.map((c) => `- \`${c.variable}\`: resolved to \`${c.resolved}\``).join("\n")}`;
  }

  return section;
}

// ── 3. Typography Rules ─────────────────────────────────────────────────────

function generateTypography(tokens: AggregatedTokens): string {
  const { fontFamilies, typeScale, fontSources } = tokens.typography;

  let section = `## 3. Typography Rules

### Font Family
- **Primary:** \`${fontFamilies[0] || "system-ui"}\``;

  if (fontFamilies.length > 1) {
    section += `\n- **Secondary:** \`${fontFamilies.slice(1).join("`, `")}\``;
  }

  if (fontSources.length > 0) {
    section += `

### Font Sources
${fontSources.map((s) => `- ${s}`).join("\n")}`;
  }

  if (typeScale.length > 0) {
    section += `

### Hierarchy

| Role | Font | Size | Weight | Line Height | Letter Spacing | Transform |
|------|------|------|--------|-------------|----------------|-----------|
${typeScale.slice(0, 20).map((t) => {
  const fontShort = t.fontFamily.split(",")[0].trim().replace(/['"]/g, "");
  const role = getTypographyRole(t.element, t.fontSize);
  return `| ${role} | ${fontShort} | ${t.fontSize} | ${t.fontWeight} | ${t.lineHeight} | ${t.letterSpacing} | ${t.textTransform} |`;
}).join("\n")}`;
  }

  // Typography principles
  const weights = [...new Set(typeScale.map((t) => t.fontWeight))].sort();
  section += `

### Principles
- **Weight system:** ${weights.join(", ")} — ${weights.length <= 2 ? "minimal weight variation keeps the design cohesive" : "varied weights create strong visual hierarchy"}
- **Scale range:** ${typeScale[0]?.fontSize || "?"} (largest) to ${typeScale[typeScale.length - 1]?.fontSize || "?"} (smallest)`;

  return section;
}

// ── 4. Component Stylings ───────────────────────────────────────────────────

function generateComponentStylesSection(tokens: AggregatedTokens): string {
  const { components } = tokens;
  let section = `## 4. Component Stylings`;

  // Buttons
  if (components.buttons.length > 0) {
    section += `

### Buttons`;
    for (const btn of components.buttons.slice(0, 6)) {
      const s = btn.default;
      section += `

**${capitalize(btn.variant)}${btn.text ? ` ("${btn.text}")` : ""}**
- Background: \`${s.background || "transparent"}\`
- Text: \`${s.color || "inherit"}\`
- Padding: \`${s.padding || "8px 16px"}\`
- Radius: \`${s.borderRadius || "0"}\`
- Border: \`${s.border || "none"}\`
- Font: ${s.fontSize || "16px"} weight ${s.fontWeight || "400"}
- Cursor: ${s.cursor || "pointer"}`;
      if (s.transition && s.transition !== "all 0s ease 0s" && s.transition !== "none") {
        section += `\n- Transition: \`${s.transition}\``;
      }
    }
  }

  // Cards
  if (components.cards.length > 0) {
    section += `

### Cards & Containers`;
    for (const card of components.cards.slice(0, 4)) {
      const s = card.styles;
      section += `
- Background: \`${s.background || "#ffffff"}\`
- Border: \`${s.border || "none"}\`
- Radius: \`${s.borderRadius || "0"}\``;
      if (s.boxShadow && s.boxShadow !== "none") {
        section += `\n- Shadow: \`${s.boxShadow}\``;
      }
      if (s.padding) {
        section += `\n- Padding: \`${s.padding}\``;
      }
    }
  }

  // Inputs
  if (components.inputs.length > 0) {
    section += `

### Inputs & Forms`;
    for (const input of components.inputs.slice(0, 3)) {
      const s = input.default;
      section += `
- Border: \`${s.border || "1px solid #ccc"}\`
- Radius: \`${s.borderRadius || "0"}\`
- Background: \`${s.background || "#ffffff"}\`
- Text: \`${s.color || "inherit"}\`, ${s.fontSize || "16px"}
- Padding: \`${s.padding || "8px"}\``;
    }
  }

  // Navigation
  if (components.nav) {
    const n = components.nav;
    section += `

### Navigation
- Position: \`${n.position}\`
- Background: \`${n.background}\``;
    if (n.backdropFilter !== "none") {
      section += `\n- Backdrop: \`${n.backdropFilter}\``;
    }
    section += `\n- Height: \`${n.height}\``;
    if (n.borderBottom && n.borderBottom !== "none" && !n.borderBottom.includes("0px")) {
      section += `\n- Border bottom: \`${n.borderBottom}\``;
    }
    if (n.linkStyles.fontSize) {
      section += `\n- Link font: ${n.linkStyles.fontSize} weight ${n.linkStyles.fontWeight || "400"}, color \`${n.linkStyles.color || "inherit"}\``;
    }
    if (n.ctaStyles) {
      section += `\n- CTA: \`${n.ctaStyles.background}\` bg, \`${n.ctaStyles.color}\` text, radius \`${n.ctaStyles.borderRadius}\``;
    }
  }

  if (components.buttons.length === 0 && components.cards.length === 0 && !components.nav) {
    section += `\n\nNo component patterns extracted — site may use non-standard selectors.`;
  }

  return section;
}

// ── 5. Layout Principles ────────────────────────────────────────────────────

function generateLayoutPrinciples(tokens: AggregatedTokens): string {
  const { spacing, borders } = tokens;

  let section = `## 5. Layout Principles

### Spacing System
- **Scale:** [${spacing.scale.join(", ")}] (px)
- **Base unit:** ${detectBaseUnit(spacing.scale)}px`;

  if (spacing.paddingPatterns.length > 0) {
    section += `

### Common Padding Values
${spacing.paddingPatterns.slice(0, 8).map((p) => `- \`${p.value}\` (${p.frequency}x)`).join("\n")}`;
  }

  if (spacing.gapPatterns.length > 0) {
    section += `

### Common Gap Values
${spacing.gapPatterns.slice(0, 8).map((p) => `- \`${p.value}\` (${p.frequency}x)`).join("\n")}`;
  }

  section += `

### Border Radius Scale`;
  if (borders.radii.length > 0) {
    const sortedRadii = borders.radii
      .map((r) => ({ raw: r, px: parseFloat(r) }))
      .filter((r) => !isNaN(r.px))
      .sort((a, b) => a.px - b.px);

    for (const r of sortedRadii) {
      const label =
        r.px <= 2 ? "Micro" : r.px <= 4 ? "Small" : r.px <= 8 ? "Standard" : r.px <= 12 ? "Medium" : r.px <= 20 ? "Large" : "Extra Large";
      section += `\n- **${label}** (\`${r.raw}\`): ${r.px <= 4 ? "Inputs, badges, small elements" : r.px <= 8 ? "Buttons, cards, standard components" : r.px <= 16 ? "Featured cards, modals" : "Pills, avatars, large rounding"}`;
    }
  } else {
    section += `\nNo non-zero border radii found — sharp, geometric aesthetic.`;
  }

  return section;
}

// ── 6. Depth & Elevation ────────────────────────────────────────────────────

function generateDepthAndElevation(tokens: AggregatedTokens): string {
  const { shadows } = tokens;
  const levels = classifyShadows(shadows.boxShadows);

  let section = `## 6. Depth & Elevation

| Level | Name | Shadow | Use |
|-------|------|--------|-----|
| 0 | Flat | none | Page background, inline text |`;

  for (const level of levels) {
    section += `\n| ${level.level} | ${level.name} | \`${level.shadow}\` | ${level.usage} |`;
  }

  if (shadows.textShadows.length > 0) {
    section += `

### Text Shadows
${shadows.textShadows.map((s) => `- \`${s}\``).join("\n")}`;
  }

  return section;
}

// ── 7. Do's and Don'ts ──────────────────────────────────────────────────────

function generateDosAndDonts(tokens: AggregatedTokens): string {
  const { typography, colors, borders, shadows, spacing, components } = tokens;

  const dos: string[] = [];
  const donts: string[] = [];

  // Typography rules
  const primaryFont = typography.fontFamilies[0]?.split(",")[0].trim().replace(/['"]/g, "") || "the primary font";
  dos.push(`Use \`${primaryFont}\` as the primary typeface for all UI text`);

  const weights = [...new Set(typography.typeScale.map((t) => t.fontWeight))];
  if (weights.length <= 3) {
    dos.push(`Stick to weights ${weights.join("/")} — this system uses ${weights.length <= 2 ? "minimal" : "limited"} weight variation`);
    donts.push(`Don't introduce new font weights beyond ${weights.join(", ")} — they're not part of this design system`);
  }

  // Color rules
  const primaryText = colors.palette.find((c) => c.usage === "text");
  if (primaryText && primaryText.hex !== "#000000") {
    dos.push(`Use \`${primaryText.hex}\` for heading text instead of pure black`);
    donts.push(`Don't use pure black (\`#000000\`) for text — always use \`${primaryText.hex}\``);
  }

  const primaryAccent = colors.palette.find((c) => c.usage === "accent");
  if (primaryAccent) {
    dos.push(`Use \`${primaryAccent.hex}\` as the primary interactive/CTA color`);
    donts.push(`Don't substitute a different accent color for interactive elements — \`${primaryAccent.hex}\` is the brand accent`);
  }

  // Border radius rules
  const radiiNums = borders.radii.map((r) => parseFloat(r)).filter((n) => !isNaN(n) && n > 0);
  if (radiiNums.length > 0) {
    const maxRadius = Math.max(...radiiNums);
    if (maxRadius <= 8) {
      dos.push(`Keep border-radius between ${Math.min(...radiiNums)}px-${maxRadius}px — conservative rounding is intentional`);
      donts.push(`Don't use large border-radius (16px+, pill shapes) — this design system favors ${maxRadius <= 4 ? "sharp, geometric" : "conservative, precise"} corners`);
    }
  }

  // Shadow rules
  if (shadows.boxShadows.length > 0) {
    dos.push(`Apply the extracted shadow values for elevation — they're part of the design's depth language`);
    donts.push(`Don't use generic shadow utilities (e.g., \`shadow-md\`) — use the exact extracted shadow values`);
  }

  // Spacing rules
  if (spacing.scale.length > 0) {
    dos.push(`Use the spacing scale [${spacing.scale.slice(0, 8).join(", ")}]px for all padding, margin, and gap`);
    donts.push(`Don't use arbitrary spacing values — stick to the extracted scale`);
  }

  // Component rules
  if (components.buttons.length > 0) {
    const primaryBtn = components.buttons.find((b) => b.variant === "primary");
    if (primaryBtn?.default.borderRadius) {
      dos.push(`Buttons use \`${primaryBtn.default.borderRadius}\` radius — match this exactly`);
    }
  }

  // Generic guardrails
  donts.push(`Don't inject generic AI aesthetics — no default Inter font, no purple gradients unless they appear in the palette above`);
  donts.push(`Don't override extracted values with framework defaults (Tailwind, Bootstrap, etc.)`);

  return `## 7. Do's and Don'ts

### Do
${dos.map((d) => `- ${d}`).join("\n")}

### Don't
${donts.map((d) => `- ${d}`).join("\n")}`;
}

// ── 8. Responsive Behavior ──────────────────────────────────────────────────

function generateResponsiveBehavior(tokens: AggregatedTokens): string {
  const { breakpoints, typography } = tokens;

  let section = `## 8. Responsive Behavior

### Breakpoints`;

  if (breakpoints.breakpoints.length > 0) {
    section += `
| Name | Width | Key Changes |
|------|-------|-------------|`;

    const sorted = [...breakpoints.breakpoints].sort((a, b) => a.width - b.width);
    for (const bp of sorted) {
      const name =
        bp.width <= 480 ? "Mobile" : bp.width <= 768 ? "Tablet" : bp.width <= 1024 ? "Desktop" : "Large Desktop";
      const changes =
        bp.width <= 480
          ? "Single column, reduced heading sizes, stacked cards"
          : bp.width <= 768
            ? "2-column grids, moderate padding"
            : bp.width <= 1024
              ? "Full layout, multi-column feature grids"
              : "Centered content with generous margins";
      section += `\n| ${name} | ${bp.width}px | ${changes} |`;
    }
  } else {
    section += `\nNo media query breakpoints extracted.`;
  }

  // Typography collapsing
  const headings = typography.typeScale.filter((t) => ["h1", "h2", "h3"].includes(t.element));
  if (headings.length > 0) {
    section += `

### Collapsing Strategy
- Hero heading: ${headings[0]?.fontSize || "?"} → reduce to ~${Math.round(parseFloat(headings[0]?.fontSize || "32") * 0.7)}px on mobile
- Navigation: horizontal links → hamburger toggle on mobile
- Feature cards: multi-column → single column stacked
- Section spacing: reduce by ~40% on mobile`;
  }

  section += `

### Touch Targets
- All interactive elements should be minimum 44x44px
- Buttons maintain comfortable padding on mobile
- Adequate spacing between tap targets`;

  return section;
}

// ── 9. Agent Prompt Guide ───────────────────────────────────────────────────

function generateAgentPromptGuide(tokens: AggregatedTokens): string {
  const { colors, typography, shadows, borders, components } = tokens;

  const primaryFont = typography.fontFamilies[0]?.split(",")[0].trim().replace(/['"]/g, "") || "system-ui";
  const headingColor = colors.palette.find((c) => c.usage === "text")?.hex || "#000";
  const bodyColor = colors.palette.filter((c) => c.usage === "text")[1]?.hex || "#666";
  const bgColor = colors.backgrounds[0] || "#fff";
  const accentColor = colors.palette.find((c) => c.usage === "accent")?.hex || colors.palette[0]?.hex || "#333";
  const borderColor = colors.borderColors[0] || "#e5e5e5";
  const primaryShadow = shadows.boxShadows[0] || "none";
  const mainRadius = borders.radii[0] || "0";

  let section = `## 9. Agent Prompt Guide

### Quick Color Reference
- **Primary CTA:** \`${accentColor}\`
- **Background:** \`${bgColor}\`
- **Heading text:** \`${headingColor}\`
- **Body text:** \`${bodyColor}\`
- **Border:** \`${borderColor}\`
- **Link/accent:** \`${accentColor}\`

### Example Component Prompts`;

  // Hero section prompt
  const heroEntry = typography.typeScale.find((t) => t.element === "h1") || typography.typeScale[0];
  if (heroEntry) {
    section += `

- "Create a hero section on \`${bgColor}\` background. Headline at ${heroEntry.fontSize} ${primaryFont} weight ${heroEntry.fontWeight}, line-height ${heroEntry.lineHeight}, letter-spacing ${heroEntry.letterSpacing}, color \`${headingColor}\`. Subtitle at ${typography.typeScale.find((t) => t.element === "p")?.fontSize || "16px"} weight ${typography.typeScale.find((t) => t.element === "p")?.fontWeight || "400"}, color \`${bodyColor}\`. CTA button (\`${accentColor}\` background, white text, ${mainRadius} radius)."`;
  }

  // Card prompt
  if (components.cards.length > 0 || primaryShadow !== "none") {
    section += `

- "Design a card: \`${bgColor}\` background, \`1px solid ${borderColor}\` border, ${mainRadius} radius. Shadow: \`${primaryShadow}\`. Title at ${typography.typeScale.find((t) => ["h3", "h4"].includes(t.element))?.fontSize || "20px"} ${primaryFont} weight ${typography.typeScale.find((t) => ["h3", "h4"].includes(t.element))?.fontWeight || "600"}, color \`${headingColor}\`. Body at 16px, \`${bodyColor}\`."`;
  }

  // Button prompt
  if (components.buttons.length > 0) {
    const btn = components.buttons[0];
    section += `

- "Build a button: \`${btn.default.background}\` background, \`${btn.default.color}\` text, \`${btn.default.borderRadius}\` radius, padding \`${btn.default.padding}\`, font ${btn.default.fontSize} weight ${btn.default.fontWeight}."`;
  }

  // Nav prompt
  if (components.nav) {
    section += `

- "Create navigation: ${components.nav.position} position, \`${components.nav.background}\` background${components.nav.backdropFilter !== "none" ? `, backdrop-filter: ${components.nav.backdropFilter}` : ""}. Links at ${components.nav.linkStyles.fontSize || "14px"} weight ${components.nav.linkStyles.fontWeight || "400"}, color \`${components.nav.linkStyles.color || headingColor}\`. ${components.nav.ctaStyles ? `CTA: \`${components.nav.ctaStyles.background}\` bg, \`${components.nav.ctaStyles.color}\` text.` : ""}"`;
  }

  section += `

### Iteration Guide
1. Use \`${primaryFont}\` for all text — it defines the visual identity
2. Heading color is \`${headingColor}\`, body text is \`${bodyColor}\`
3. Primary accent/CTA color: \`${accentColor}\`
4. Border radius stays at \`${mainRadius}\` for standard components
5. Use the spacing scale: [${tokens.spacing.scale.slice(0, 8).join(", ")}]px
6. Shadow formula: \`${primaryShadow}\`
7. All borders use \`${borderColor}\``;

  return section;
}

// ── 10. Raw CSS Variables (Appendix) ────────────────────────────────────────
// Note: This is appended after the agent prompt guide as reference material

// ── Helpers ─────────────────────────────────────────────────────────────────

function isColorDark(color: string): boolean {
  const hex = color.replace("#", "");
  if (hex.length !== 6) return false;
  const r = parseInt(hex.substring(0, 2), 16);
  const g = parseInt(hex.substring(2, 4), 16);
  const b = parseInt(hex.substring(4, 6), 16);
  const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  return luminance < 0.5;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function getTypographyRole(element: string, fontSize: string): string {
  const size = parseFloat(fontSize);
  if (element === "h1" || size >= 40) return "Display Hero";
  if (element === "h2" || size >= 28) return "Section Heading";
  if (element === "h3" || size >= 22) return "Sub-heading";
  if (element === "h4" || size >= 18) return "Body Large";
  if (element === "h5") return "Label";
  if (element === "h6") return "Caption";
  if (element === "button") return "Button";
  if (element === "input") return "Input";
  if (element === "a") return "Link";
  if (element === "li") return "List Item";
  if (element === "label") return "Label";
  if (element === "figcaption") return "Caption";
  if (size >= 18) return "Body Large";
  if (size >= 14) return "Body";
  if (size >= 12) return "Caption";
  return "Micro";
}

function detectBaseUnit(scale: number[]): number {
  if (scale.length < 2) return 4;
  const diffs = scale.slice(1).map((v, i) => v - scale[i]);
  const gcd = diffs.reduce((a, b) => {
    while (b) { [a, b] = [b, a % b]; }
    return Math.abs(a);
  });
  return gcd > 0 && gcd <= 8 ? gcd : 4;
}

function classifyShadows(shadows: string[]): ElevationLevel[] {
  if (shadows.length === 0) return [];

  // Sort by estimated "intensity" (blur radius)
  const parsed = shadows.map((s) => {
    const blurMatch = s.match(/(\d+)px\s+(\d+)px\s+(\d+)px/);
    const blur = blurMatch ? parseInt(blurMatch[3]) : 0;
    return { shadow: s, blur };
  }).sort((a, b) => a.blur - b.blur);

  const levels: ElevationLevel[] = [];
  const names = ["Subtle", "Standard", "Elevated", "Deep", "Dramatic"];
  const usages = [
    "Hover hints, subtle lift",
    "Cards, content panels",
    "Featured cards, dropdowns",
    "Modals, floating panels",
    "Maximum emphasis, overlays",
  ];

  for (let i = 0; i < Math.min(parsed.length, 5); i++) {
    levels.push({
      name: names[i] || `Level ${i + 1}`,
      level: i + 1,
      shadow: parsed[i].shadow,
      usage: usages[i] || "Custom elevation",
    });
  }

  return levels;
}
