import type { AggregatedTokens } from "@/lib/extraction/types";

/**
 * Generates the complete Markdown prompt file from aggregated design tokens.
 * This is the primary output of the application — a structured Claude Code prompt
 * that establishes the scraped design as ground truth.
 */
export function generateMarkdown(tokens: AggregatedTokens): string {
  const sections = [
    generateHeader(tokens),
    generateFidelityHierarchy(),
    generateTypographySection(tokens),
    generateColorsSection(tokens),
    generateSpacingSection(tokens),
    generateBordersSection(tokens),
    generateShadowsSection(tokens),
    generateMotionSection(tokens),
    generateBreakpointsSection(tokens),
    generateAssetsSection(tokens),
    generateRawVariablesSection(tokens),
    generateChecklist(),
  ];

  return sections.join("\n\n---\n\n");
}

// ── Header ──────────────────────────────────────────────────────────────────

function generateHeader(tokens: AggregatedTokens): string {
  const urlList = tokens.sourceUrls.map((u) => `- ${u}`).join("\n");
  return `# Frontend DNA: Design System Prompt

> **Auto-generated by frontend-dna**
> Source${tokens.sourceUrls.length > 1 ? "s" : ""}:
${urlList}
>
> Use this as the ground-truth design system when building UI components.
> Generated: ${new Date().toISOString()}`;
}

// ── Design Fidelity Hierarchy ───────────────────────────────────────────────

function generateFidelityHierarchy(): string {
  return `## Design Fidelity Hierarchy

> **CRITICAL INSTRUCTION FOR AI CODE GENERATION**

The following tokens were extracted directly from live website(s) using computed styles.
They represent the **actual design system in production** and MUST take absolute priority
over any AI defaults, training data aesthetics, or "common patterns."

### Rules:
1. **Use these exact values** — do not approximate, round, or substitute
2. **If a token exists here, it overrides your training defaults** — no Inter, no Roboto, no purple gradients unless they appear below
3. **If something is not specified here**, you may use reasonable defaults that harmonize with the extracted system
4. **When in doubt, match the source** — the scraped site is the design authority, not your aesthetic preferences
5. **Never inject generic AI aesthetics** — no cookie-cutter shadcn defaults, no recycled color schemes`;
}

// ── Typography ──────────────────────────────────────────────────────────────

function generateTypographySection(tokens: AggregatedTokens): string {
  const { fontFamilies, typeScale, fontSources } = tokens.typography;

  let section = `## 1. Typography

### Font Families
${fontFamilies.map((f) => `- \`${f}\``).join("\n")}`;

  if (fontSources.length > 0) {
    section += `

### Font Sources
${fontSources.map((s) => `- ${s}`).join("\n")}`;
  }

  if (typeScale.length > 0) {
    section += `

### Type Scale
| Element | Font Family | Size | Weight | Line Height | Letter Spacing | Transform |
|---------|-------------|------|--------|-------------|----------------|-----------|
${typeScale
  .map(
    (t) =>
      `| ${t.element} | \`${t.fontFamily.split(",")[0].trim()}\` | ${t.fontSize} | ${t.fontWeight} | ${t.lineHeight} | ${t.letterSpacing} | ${t.textTransform} |`
  )
  .join("\n")}`;
  }

  return section;
}

// ── Colors & Theme ──────────────────────────────────────────────────────────

function generateColorsSection(tokens: AggregatedTokens): string {
  const { palette, cssVariableColors, backgrounds, textColors, borderColors } =
    tokens.colors;

  let section = `## 2. Colors & Theme`;

  // CSS Variable Colors
  const varEntries = Object.entries(cssVariableColors);
  if (varEntries.length > 0) {
    section += `

### CSS Custom Properties (Colors)
\`\`\`css
:root {
${varEntries.map(([k, v]) => `  ${k}: ${v};`).join("\n")}
}
\`\`\``;
  }

  // Full Palette
  if (palette.length > 0) {
    section += `

### Full Palette
| Hex | HSL | Usage | Frequency |
|-----|-----|-------|-----------|
${palette
  .slice(0, 30) // Cap at 30 most frequent
  .map((c) => `| \`${c.hex}\` | \`${c.hsl}\` | ${c.usage} | ${c.frequency} |`)
  .join("\n")}`;
  }

  // Semantic groupings
  section += `

### Semantic Color Mapping
- **Text colors:** ${textColors.slice(0, 10).map((c) => `\`${c}\``).join(", ") || "none extracted"}
- **Background colors:** ${backgrounds.slice(0, 10).map((c) => `\`${c}\``).join(", ") || "none extracted"}
- **Border colors:** ${borderColors.slice(0, 10).map((c) => `\`${c}\``).join(", ") || "none extracted"}`;

  // Conflict notes
  if (tokens.conflicts.length > 0) {
    section += `

### Variable Conflicts (Multi-URL)
${tokens.conflicts
  .map(
    (c) =>
      `- \`${c.variable}\`: resolved to \`${c.resolved}\` (conflicts: ${c.values.map((v) => `${v.value} from ${v.url}`).join(", ")})`
  )
  .join("\n")}`;
  }

  return section;
}

// ── Spatial Composition ─────────────────────────────────────────────────────

function generateSpacingSection(tokens: AggregatedTokens): string {
  const { scale, paddingPatterns, gapPatterns } = tokens.spacing;

  let section = `## 3. Spatial Composition

### Spacing Scale
\`[${scale.join(", ")}]\` (px)

Use these values for all padding, margin, and gap properties.`;

  if (paddingPatterns.length > 0) {
    section += `

### Common Padding Values
${paddingPatterns
  .slice(0, 10)
  .map((p) => `- \`${p.value}\` (used ${p.frequency}x)`)
  .join("\n")}`;
  }

  if (gapPatterns.length > 0) {
    section += `

### Common Gap Values
${gapPatterns
  .slice(0, 10)
  .map((p) => `- \`${p.value}\` (used ${p.frequency}x)`)
  .join("\n")}`;
  }

  return section;
}

// ── Borders & Radii ─────────────────────────────────────────────────────────

function generateBordersSection(tokens: AggregatedTokens): string {
  const { radii, widths, styles } = tokens.borders;

  return `## 4. Borders & Radii

### Border Radii
${radii.length > 0 ? radii.map((r) => `- \`${r}\``).join("\n") : "No non-zero border radii found."}

### Border Widths
${widths.length > 0 ? widths.map((w) => `- \`${w}\``).join("\n") : "No explicit border widths found."}

### Border Styles
${styles.length > 0 ? styles.map((s) => `- \`${s}\``).join("\n") : "No explicit border styles found."}`;
}

// ── Shadows & Elevation ─────────────────────────────────────────────────────

function generateShadowsSection(tokens: AggregatedTokens): string {
  const { boxShadows, textShadows } = tokens.shadows;

  let section = `## 5. Shadows & Elevation`;

  if (boxShadows.length > 0) {
    section += `

### Box Shadows
\`\`\`css
${boxShadows.map((s, i) => `/* shadow-${i + 1} */ box-shadow: ${s};`).join("\n")}
\`\`\``;
  } else {
    section += `

No box shadows extracted.`;
  }

  if (textShadows.length > 0) {
    section += `

### Text Shadows
\`\`\`css
${textShadows.map((s, i) => `/* text-shadow-${i + 1} */ text-shadow: ${s};`).join("\n")}
\`\`\``;
  }

  return section;
}

// ── Motion & Interaction ────────────────────────────────────────────────────

function generateMotionSection(tokens: AggregatedTokens): string {
  const { transitions, durations, easings, keyframes } = tokens.motion;

  let section = `## 6. Motion & Interaction

### Transition Durations
${durations.length > 0 ? durations.map((d) => `- \`${d}\``).join("\n") : "No custom durations found."}

### Timing Functions
${easings.length > 0 ? easings.map((e) => `- \`${e}\``).join("\n") : "No custom easings found."}`;

  if (transitions.length > 0) {
    section += `

### Full Transitions
${transitions.slice(0, 15).map((t) => `- \`${t}\``).join("\n")}`;
  }

  if (keyframes.length > 0) {
    section += `

### Keyframe Animations
\`\`\`css
${keyframes.map((k) => k.cssText).join("\n\n")}
\`\`\``;
  }

  return section;
}

// ── Responsive Breakpoints ──────────────────────────────────────────────────

function generateBreakpointsSection(tokens: AggregatedTokens): string {
  const { breakpoints } = tokens.breakpoints;

  if (breakpoints.length === 0) {
    return `## 7. Responsive Breakpoints

No media query breakpoints extracted.`;
  }

  return `## 7. Responsive Breakpoints

| Width (px) | Media Query |
|------------|-------------|
${breakpoints.map((bp) => `| ${bp.width} | \`${bp.query}\` |`).join("\n")}`;
}

// ── Assets ──────────────────────────────────────────────────────────────────

function generateAssetsSection(tokens: AggregatedTokens): string {
  const { favicon, ogImage, logos } = tokens.assets;

  return `## 8. Assets

- **Favicon:** ${favicon || "not found"}
- **OG Image:** ${ogImage || "not found"}
- **Logos:** ${logos.length > 0 ? logos.join(", ") : "none found"}`;
}

// ── Raw CSS Variables ───────────────────────────────────────────────────────

function generateRawVariablesSection(tokens: AggregatedTokens): string {
  const entries = Object.entries(tokens.cssVariables);

  if (entries.length === 0) {
    return `## 9. Raw CSS Custom Properties

No CSS custom properties found.`;
  }

  return `## 9. Raw CSS Custom Properties (Complete)

\`\`\`css
:root {
${entries.map(([k, v]) => `  ${k}: ${v};`).join("\n")}
}
\`\`\``;
}

// ── Pre-Delivery Checklist ──────────────────────────────────────────────────

function generateChecklist(): string {
  return `## Pre-Delivery Checklist

Before delivering any component built with this design system, verify:

- [ ] All colors match the extracted palette exactly (no AI-generated substitutions)
- [ ] Typography uses the exact font families, sizes, and weights listed above
- [ ] Spacing follows the extracted scale (not Tailwind/framework defaults)
- [ ] Border radii match extracted values precisely
- [ ] WCAG 2.1 AA contrast ratios met for all text/background combinations (minimum 4.5:1)
- [ ] Touch targets are minimum 44x44px on interactive elements
- [ ] Shadows use the exact extracted values (not generic elevation systems)
- [ ] Transitions use the extracted durations and easings
- [ ] Responsive breakpoints align with extracted values
- [ ] No generic AI aesthetics leaked in (Inter font, purple gradients, default blue links)
- [ ] Component proportions match the source site's visual rhythm
- [ ] Background patterns/gradients replicate the source, not AI defaults`;
}
